FIX Update partial logic to work in image build

diff --git a/templates/partials/ensure-no-defaults.dockerfile.j2 b/templates/partials/ensure-no-defaults.dockerfile.j2
--- a/templates/partials/ensure-no-defaults.dockerfile.j2
+++ b/templates/partials/ensure-no-defaults.dockerfile.j2
@@ -1,5 +1,6 @@
 {# This partial file is used to ensure there are no packages from the defaults conda channel #}
 
 {# Check for defaults packages in rapids env #}
-ENV CONDA_DEFAULT_PKG_NUM=`conda list | awk '{ print $4}' | grep defaults | wc -l`
-RUN if [[ ${CONDA_DEFAULT_PKG_NUM} -eq 0 ]]; then echo "ERROR: Packages from the default conda channel detected"; exit 1; fi
+RUN source activate rapids \
+    && CONDA_DEFAULT_PKG_NUM=`conda list | awk '{ print $4 }' | grep defaults | wc -l` \
+    && if [[ ${CONDA_DEFAULT_PKG_NUM} -ne 0 ]]; then echo "ERROR: Packages from the default conda channel detected"; exit 1; fi
